// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGj1y9uVHs2R9kkqYQo9_DGo0che6l-Qo',
    appId: '1:980782648984:web:658f4884eca3c312b88aed',
    messagingSenderId: '980782648984',
    projectId: 'diazo-e084d',
    authDomain: 'diazo-e084d.firebaseapp.com',
    storageBucket: 'diazo-e084d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ_jXXVyu_j-Heo55wkN3n5aIo5uoWtQM',
    appId: '1:980782648984:android:47f8252648d40f6bb88aed',
    messagingSenderId: '980782648984',
    projectId: 'diazo-e084d',
    storageBucket: 'diazo-e084d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa3eHPlHVLshIfga0GpwgxhKqMmDP-I4A',
    appId: '1:980782648984:ios:874f6a480656cd28b88aed',
    messagingSenderId: '980782648984',
    projectId: 'diazo-e084d',
    storageBucket: 'diazo-e084d.appspot.com',
    androidClientId: '980782648984-8084eb6oaku5n4kvoh5upg8vvb68uk5d.apps.googleusercontent.com',
    iosClientId: '980782648984-vvvicugv9fmjrhoapm5rkq1cls1509f4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa3eHPlHVLshIfga0GpwgxhKqMmDP-I4A',
    appId: '1:980782648984:ios:874f6a480656cd28b88aed',
    messagingSenderId: '980782648984',
    projectId: 'diazo-e084d',
    storageBucket: 'diazo-e084d.appspot.com',
    androidClientId: '980782648984-8084eb6oaku5n4kvoh5upg8vvb68uk5d.apps.googleusercontent.com',
    iosClientId: '980782648984-vvvicugv9fmjrhoapm5rkq1cls1509f4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );
}
